version: '3.5'  
services:  
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: unless-stopped

  web:
    build: .
    container_name: web_container
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"
    links:
      - redis
    networks:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: unless-stopped

  db:
    image: postgres:alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Postgresql2019}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - '6379:6379'
    networks:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: unless-stopped
  
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
